### ISSUE TITLE
Don't post the number of articles found

### ISSUE THREAD

**Issue by 4e554c4c** [so-okada/toXiv#1]
I would prefer if the arXiv bots did not post `[<date>, <n> new articles found for <category>]`. I don't believe this is useful for an individual's feed (and is not a useful post by itself).

**Comment by so-okada** [comment]
Sometimes, it seems fun for individuals.
https://twitter.com/AndresECaicedo1/status/1487973972897452032

Also, in my opinion, it gives daily summaries, records to look back, and clearly separate toots/boosts for different days.

**Comment by 4e554c4c** [comment]
I believe that "no new articles found" is more useful than "3 new articles found".
But if this is intentional and people are enjoying it i have no qualms  :smile:  I can always add a user filter for this kind of post.

In general I believe something like this would be more useful as an ActivityPub-speaking server that could deliver articles at creation time and translate all existing documents to an AP-compatible format (since "proxy-like" software is hard to write on the mastodon API, but is not too hard standalone).
needless to say this is out-of-scope for this project, and not all of my desires can be served by it :sweat:
