### ISSUE TITLE
Consider removing the arxiv image from post

### ISSUE THREAD

**Issue by nielsle** [so-okada/toXiv#2]
When I read arxiv-bot posts in he standard web interface, then he post is dominated by a large image with the arxiv logo. Please consider removing this image from the posts, because it eats up space in the feed.

<img width="442" alt="image" src="https://github.com/so-okada/toXiv/assets/292118/755024fe-69f7-4cce-8f95-46c7a256b1b2">

As far as I can see the image is smaller on some webinterfaces, so perhaps this is a settings issue. But I still think that it would be useful to remove the logo

<img width="465" alt="image" src="https://github.com/so-okada/toXiv/assets/292118/fa258746-d17f-4919-a33e-066132b52b6d">

PS: Thank you for a great bot. It is really useful

**Comment by so-okada** [comment]
Which setting do you know?

**Comment by nielsle** [comment]
Here are my settings.

<img width="359" alt="image" src="https://github.com/so-okada/toXiv/assets/292118/a30ef01f-e2a7-45d9-9c94-3c3bec6b4094">
<img width="375" alt="image" src="https://github.com/so-okada/toXiv/assets/292118/41b34151-aa89-4a4b-a205-b53e93cd3658">

**Comment by nielsle** [comment]
I am using the web interface of https://mastodon.social

**Comment by so-okada** [comment]
> Here are my settings.
> 
> <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/292118/302042254-a30ef01f-e2a7-45d9-9c94-3c3bec6b4094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzE1MjYsIm5iZiI6MTcwNzAzMTIyNiwicGF0aCI6Ii8yOTIxMTgvMzAyMDQyMjU0LWEzMGVmMDFmLWUyYTctNDVkOS05Yzk0LTNjM2JlYzZiNDA5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzIwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGZmNDhjZGFmNTkyZDkzY2I3NWRjZmJjODdjZTllOWIzOTNmMzZlNjk1MWYzZjU0MzQ5NzVmNDdkMGM4OWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fimuegMkkJvx5THR7qPAHIYBON71zwK5VQ6Uo34oeso"> <img alt="image" width="375" src="https://private-user-images.githubusercontent.com/292118/302042275-41b34151-aa89-4a4b-a205-b53e93cd3658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzE1MjYsIm5iZiI6MTcwNzAzMTIyNiwicGF0aCI6Ii8yOTIxMTgvMzAyMDQyMjc1LTQxYjM0MTUxLWFhODktNGE0Yi1hMjA1LWI1M2U5M2NkMzY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzIwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTRiZWEyNmJmZDliMDcwMWIwNDcwN2YyNTQxN2QzNTJlYjk4ODM1MDQ1MGE4NDA2NTFkYjBmNTEzMzY1MWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lUOHB9Y4LFdznG2bp795WBLLbfyoVAvQhXtZBmkIYxc">

One of my toXiv bots has the following, but I do not think it has a setting for smaller images.
![Screenshot from 2024-02-04 16-26-47](https://github.com/so-okada/toXiv/assets/11512333/656e306e-593d-4807-80a4-73c014c4ea4b)

**Comment by so-okada** [comment]
> I am using the web interface of https://mastodon.social

Do you mean you get the following toot when you post on the instance?
https://private-user-images.githubusercontent.com/292118/302041200-fa258746-d17f-4919-a33e-066132b52b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzIwNjUsIm5iZiI6MTcwNzAzMTc2NSwicGF0aCI6Ii8yOTIxMTgvMzAyMDQxMjAwLWZhMjU4NzQ2LWQxN2YtNDkxOS1hMzNlLTA2NjEzMmI1MmI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzI5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTNmMzY2NjAzNzEzMTQ3NzA2MGQ0MDY0ODViNjg2MmZkZTE2OGRlMDFiYTYzOGQ2ZjRiZmM1MGRhZWFhOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l2p_JDqROn1By8ojweojtJj_ysbBwTO0oMAxn7fgn08

**Comment by so-okada** [comment]
> Here are my settings.
> 
> <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/292118/302042254-a30ef01f-e2a7-45d9-9c94-3c3bec6b4094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMyNDAsIm5iZiI6MTcwNzAzMjk0MCwicGF0aCI6Ii8yOTIxMTgvMzAyMDQyMjU0LWEzMGVmMDFmLWUyYTctNDVkOS05Yzk0LTNjM2JlYzZiNDA5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjhkZjJkZTc3YWU3NTE5ZWU3ZWJjZWYwNmJiMmUyNGI2Y2I4OGZjMzcyZTYwZjZiNjExNzY2ZTY5YWQ3ZWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PxnfW-sBaFU2iyDTaUlHUW2EI2B1CI0U640dkBqjWUo"> <img alt="image" width="375" src="https://private-user-images.githubusercontent.com/292118/302042275-41b34151-aa89-4a4b-a205-b53e93cd3658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMyNDAsIm5iZiI6MTcwNzAzMjk0MCwicGF0aCI6Ii8yOTIxMTgvMzAyMDQyMjc1LTQxYjM0MTUxLWFhODktNGE0Yi1hMjA1LWI1M2U5M2NkMzY1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWFmMDk0ZjRmOWVlMzRmNjE5MWQ3MGEyN2M5NzY0YjJiZTdjNzhhYjY1ZmE2ZmY4OWQyNzFiZmEyMTg4NzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vuqtOlolcoAZE8flaAU4ZM7oA6pUbmx508pvVxX8Z7c">

Here is one of the toXiv bots, but I do not think this has a setting for publishing smaller preview link images.
![Screenshot from 2024-02-04 16-26-47](https://github.com/so-okada/toXiv/assets/11512333/dbb4a943-2ca5-4475-bbe0-1b8977c5c511)

But, I found this https://github.com/mastodon/mastodon/issues/19984 on mastodon custom css.
![Screenshot from 2024-02-04 16-58-42](https://github.com/so-okada/toXiv/assets/11512333/5e61a1cf-15fd-4064-a61d-593288931d4b)
I am not really familiar with the mastodon custom css (the aforementioned url is for making images larger). Do you know an appropriate custom mastodon css for smaller preview link images?

In the meantime, if you want for your web interface, you could block the preview link images of my instance by an ad-block extension of your browser.

**Comment by nielsle** [comment]
Thank you for looking in to this. So I guess that this is a CSS-issue on my end.

The CSS is provided server-site, so I need a new server.
